title: DSPLAY Developers' Site
heading_anchors: true

plugins:
  - jekyll-remote-theme

remote_theme: pmarsceill/just-the-docs
# theme: just-the-docs

logo: "/assets/images/dsplay-logo.png"

# color_scheme: "dark"
color_scheme: dsplay

aux_links:
  "DSPLAY - Digital Signage":
    - "https://dsplay.tv"

footer_content: "Copyright &copy; 2012-2020 DSPLAY - Digital Signage. Distributed by an <a href=\"https://opensource.org/licenses/MIT\">MIT license.</a>"
